### ISSUE TITLE
I am getting this error :( 

### ISSUE THREAD

**Issue by Giopff** [sonqs/MassDM#4]
(node:14240) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\Giorgi\OneDrive - EMIS\Desktop\MassDM-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\Giorgi\OneDrive - EMIS\Desktop\MassDM-master\node_modules\discord.js\src\client\Client.js:223:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
(node:14240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled 
with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)    
(node:14240) [DEP0018] DeprecationWarning: Unhandled promise rejections 
are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Apectro** [comment]
Check ur token, also this cant be ran as the selfbot.

**Comment by 0x796935** [comment]
> Check ur token, also this cant be ran as the selfbot.

it can be ran as selfbot :D

**Comment by Apectro** [comment]
It can but, that ain't its purpose
