### ISSUE TITLE
Throws error

### ISSUE THREAD

**Issue by lowlune** [sonqs/MassDM#7]
C:\Users\lesuisfrance\Downloads\MassDM-master\MassDM-master>node index.js
Loading 2 files...
Loading 7 commands...
(node:3720) UnhandledPromiseRejectionWarning: Error: Incorrect login details wer
e provided.
    at WebSocketConnection.<anonymous> (C:\Users\lesuisfrance\Downloads\MassDM-m
aster\MassDM-master\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (C:\Users\lesuisfrance\Downloads\MassDM-maste
r\MassDM-master\node_modules\discord.js\src\client\websocket\WebSocketConnection
.js:393:10)
    at WebSocket.onClose (C:\Users\lesuisfrance\Downloads\MassDM-master\MassDM-m
aster\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (C:\Users\lesuisfrance\Downloads\MassDM-master\MassDM
-master\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\lesuisfrance\Downloads\MassDM-master\Ma
ssDM-master\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2)
(node:3720) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

C:\Users\lesuisfrance\Downloads\MassDM-master\MassDM-master>

**Comment by lowlune** [comment]
I fixed it with replacing the token. Another error happened when messaged /dm and entered message:

C:\Users\lesuisfrance\Downloads\MassDM-master\MassDM-master>node index.js
Loading 2 files...
Loading 7 commands...
|
|    Advanced MassDM
|   Made by swirls#000
|
| Last Update: 16.6.2020
|
(node:2312) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Object.module.exports.execute (C:\Users\lesuisfrance\Downloads\MassDM-master\MassDM-master\commands\MassDM\dm.js:24:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a c
atch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `
--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminat
e the Node.js process with a non-zero exit code.


Can you please make better documentation to this? It looks very good but I cant run it.

**Comment by Apectro** [comment]
What version of djs are you using?

**Comment by lowlune** [comment]
14.15.5

**Comment by Apectro** [comment]
In your `package.json` you should have:

```
"dependencies": {
    "discord.js": "^12.1.1"
  },
```

If the version is the same as above, if not use this one.
